version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/
      - run: yarn test
