name: Node CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js v${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn format-check
    - name: Run tests
      env:
        CI: 'true'
      run: yarn test
